### ISSUE TITLE
BUG - Lectern not responsive to database connection problems

### ISSUE THREAD

**Issue by Magnitus-** [overture-stack/lectern#101]
Lectern service silently sits on bad database connection without giving feedback to orchestrator (ie, Kubernetes).

## Description

Lectern service silently sits on bad database connection without giving feedback to orchestrator (ie, Kubernetes). As such, the deployment needs to be deleted and re-created manually.

## Expected Behaviour

Either exit if it cannot communicate with the database (the ochestrator will take care of re-creating lectern with a new database connection) or return 503 on the health endpoint ("/").

## Actual Behaviour

The database connection no longer works (which is understandable in itself given the circumstances), but the process doesn't abort and doesn't report a problem on its health check endpoint.

## Possible Fix

A workaround is to pass "GET /dictionaries" (it is safe, idempotent and will try to communicate with the database and report an error if it can't) to the liveliness check instead of "GET /".

The real fix would be to make "GET /" attempt an actual communication with to the database, querying something inexpensive like count (it is more expensive than not communicating with the database, but then, the service is technically not working in any shape or form if it can't communicate with the database right?).

## Steps to Reproduce

- Run the service with a good database
- Delete the database instance and recreate it
- Observe that the service doesn't abort (which would allow the ReplicaSet resource to re-create it) and reports ok on "GET /". However, "GET /dictionaries" will show that the database connection is bad.

## Your Environment

- MongoDB 4.2, using a replicaset, no sharding (running on infra outside the K8 cluster, managed with Terraform v0.12.28)
- Lectern 1.6.5 (your image from Docker hub)
- Kubernetes: 1.17.7 (your service runs in a Deployment resource)

**Comment by rosibaj** [comment]
@Buwujiu can we get this merged for release?

**Comment by Buwujiu** [comment]
@rosibaj this ticket needs changes to helm chart as well, I'm testing in dev

**Comment by Buwujiu** [comment]
Helm chart change is in this pr: https://github.com/overture-stack/helm-charts/pull/55

**Comment by blabadi** [comment]
the chart version doesn't seem correct in dev and QA holding this ticket from release until I get more info

**Comment by blabadi** [comment]
deployed and looks good

**Comment by rosibaj** [comment]
@Magnitus- Thanks for bringing this to our attention!  We have updated this and released in version [1.8.0](https://github.com/overture-stack/lectern/releases/tag/1.8.0).  

Please let us know if you see any further issues or have any more feature suggestions!
