### ISSUE TITLE
Security Upgrade

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/lectern#111]
![image](https://user-images.githubusercontent.com/15824252/92123473-b390a800-edca-11ea-8901-2a19a41580fd.png)

**Comment by rosibaj** [comment]
hmm @Buwujiu i still see this on repo: 
![image](https://user-images.githubusercontent.com/15824252/93375046-8fe74c00-f825-11ea-9598-8c161c11f38b.png)

**Comment by Buwujiu** [comment]
fixed in this pr: https://github.com/overture-stack/lectern/pull/114

**Comment by Buwujiu** [comment]
Lectern is deployed to dev and qa(V1.9.0), awaiting release.
