### ISSUE TITLE
overture / lectern: Migrate from Dockerhub to Github Packages

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/lectern#117]

**Comment by blabadi** [comment]
jenkins now push docker images to both dockerhub and github 

![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/caed10ef-776f-4814-9ef0-36ee0bddae2a)

**Comment by blabadi** [comment]
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/621bb8f6-492a-4694-8506-95fcdf5ca1e7)

**Comment by blabadi** [comment]
deploy latest chart 0.6.0 to staging / prod
