### ISSUE TITLE
Feature Request: Use of references inside codeList

### ISSUE THREAD

**Issue by Mandloi2309** [overture-stack/lectern#173]
## Detailed Description
In the current implementation, the references to the regex and codelist can be made within schemas. However, references to a variable/element can not be made inside a codelist. For example:
If we have two codelist with values: 

`codelist_1: ['A', 'B', 'C', 'D']` and `codelist_2: ['E', 'F', 'C', 'D']`. 

Here a reference variable for the values `C` and `D` can be used for maintaining the control vocabulary in an efficient manner. 

This feature provides reusability and helps in maintaining a control vocabulary .

## Possible Implementation

> Looking for the special character `#` inside the codelist elements. This might lead to recursive reference.

> Suggestion: Including `regex` inside the codelist, allowing users to validate data based on multiple regular expressions.

**Comment by justincorrigible** [comment]
monorepo all the things!?

**Comment by joneubank** [comment]
https://github.com/overture-stack/lectern/pull/183
