### ISSUE TITLE
Make sure that Lecturn is using the DICTIONARY.WRITE permission to recognize a DCC Admin

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/lectern#26]
- [x] We need to create a policy in EGO called DICTIONARY
- [x] For the DCC admin group, give them the DICTIONARY.WRITE permission 
- [x] For AUTH for lecturn endpoints, check for this scope

**Comment by rosibaj** [comment]
Update - just needs a redeploy with the config value switched
