### ISSUE TITLE
Remove "key" field in schema

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/lectern#34]
There is an extraneous field in the schema "key"

Initially this was supposed to represent the primary_key of the schema, but since schemas represent files this is not needed anymore.

**Comment by andricDu** [comment]
Deployed to ARGO-QA as 1.1.5

**Comment by rosibaj** [comment]
tested - attempted to add a dictary with the "key" included in the schemas and was rejected.  Removal of the "key" field enabled the dictionary to be created.

**Comment by rosibaj** [comment]
thanks @andricDu !!
