### ISSUE TITLE
Fix dependency Security warnings

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/lectern#81]
https://github.com/overture-stack/lectern/network/alerts

![image](https://user-images.githubusercontent.com/15824252/78570334-d9e9f180-77f2-11ea-92bf-468c3e1adc40.png)

If you cannot see the repo warnings, please contact @rosibaj

**Comment by wajiha-oicr** [comment]
link is broken for me, but I can still try to fix this regardless

**Comment by rosibaj** [comment]
@wajiha-oicr can you see them now? i changed permissions

**Comment by wajiha-oicr** [comment]
> @wajiha-oicr can you see them now? i changed permissions

yep, I now can. thanks!
