### ISSUE TITLE
Update lectern to accept meta field references

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/lectern#92]
We have a lot of fields that are the same field (primarily ids, but also drug names) that appear in different files. 

Its hard to copy and past the same description so many times, and then manually update all the same descriptions if something changes. 

-  want to use references in `field.meta.x` in addition to `field.restrictions.x`

**Comment by rosibaj** [comment]
@jaserud Jon made some changes to allow more references to types in the dictionary.  Can you help me get this version of lectern deployed to dev then qa in argo?

**Comment by jaserud** [comment]
@rosibaj Yea I can do that. I just need to know the version of lectern??

**Comment by rosibaj** [comment]
@jaserud current commit from Jon needs a new release

**Comment by jaserud** [comment]
@rosibaj ok I can release that into dev then and I guess after its all good we can release and deploy into argo qa??

**Comment by rosibaj** [comment]
@jaserud  sounds good!

**Comment by jaserud** [comment]
@rosibaj deployed latest commit to argo dev

**Comment by rosibaj** [comment]
Tested on develop with a note referenced
- was able to add the correct references in the dictionary
- was able to compile the dictionary
- was able to successfully submit to lectern
- was able to see the dictionary resolve correctly with/without references from the get dictionary endpoint

**Comment by rosibaj** [comment]
@jaserud Can we move this to QA?

**Comment by jaserud** [comment]
@rosibaj sure. I will need some PR reviews to setup the rc branch though

**Comment by rosibaj** [comment]
maybe @joneubank can help?

**Comment by jaserud** [comment]
opened rc: https://github.com/overture-stack/lectern/pull/96

**Comment by jaserud** [comment]
@rosibaj lectern 1.6.5 deployed to argo qa

**Comment by rosibaj** [comment]
Tested on QA - lgtm! 

was able to run a successful dry run with the dictionary 49.2 so i think this is working now!

**Comment by rosibaj** [comment]
verified that i am able to retrieve the staging dictionaries - @hlminh2000 i think we can move to prod!

**Comment by rosibaj** [comment]
Dictionary 0.14 successfully submittted on production
